name:                updater
version:             0.1.0.0
github:              "nix-community/nix-vscode-extensions"
license:             BSD3
author:              "value"
maintainer:          "value"
copyright:           "value"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/value/updater#readme>

default-extensions:
- BangPatterns
- BlockArguments
- ConstraintKinds
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- ImplicitParams
- ImportQualifiedPost
- InstanceSigs
- LambdaCase
- NamedFieldPuns
- NumericUnderscores
- OverloadedLabels
- OverloadedRecordDot
- OverloadedStrings
- QuasiQuotes
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeFamilies
- ViewPatterns

dependencies:
- aeson
- async
- async-pool
- base >= 4.7 && < 5
- bytestring
- co-log
- co-log-concurrent
- data-default
- directory
- generic-lens
- hashable
- http-client
- http-conduit
- http-types
- lens
- lens-aeson
- megaparsec
- mtl
- optparse-generic
- prettyprinter
- PyF
- stm
- stm-chans
- text
- time
- unliftio
- unordered-containers
- vector
- versions
- with-utf8
- yaml

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  updater:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - updater