collectGarbage: true
logSeverity: Info
openVSX:
  pageCount: 10
  pageSize: 1000
  release:
    eamodio:
    - gitlens
    rust-lang:
    - rust-analyzer
    stkb:
    - rewrap
vscodeMarketplace:
  pageCount: 100
  pageSize: 1000
  release:
    eamodio:
    - gitlens
    GitHub:
    - copilot
    - copilot-chat
    - vscode-pull-request-github
    ms-vscode-remote:
    - remote-ssh
    rust-lang:
    - rust-analyzer
    stkb:
    - rewrap
maxMissingTimes: 10
