collectGarbage: true
garbageCollectorDelay: 10
logSeverity: Info
maxMissingTimes: 100
programTimeout: 3600
openVSX:
  enable: true
  pageCount: 10
  pageSize: 1000
  nThreads: 50
vscodeMarketplace:
  pageCount: 100
  pageSize: 1000
